-- Season default discipline split % and per-phase sport hour ramps

ALTER TABLE "SeasonPlan"
  ADD COLUMN IF NOT EXISTS "swimSplitPercent" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "bikeSplitPercent" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "runSplitPercent" DOUBLE PRECISION;

ALTER TABLE "SeasonPhase"
  ADD COLUMN IF NOT EXISTS "swimStartHours" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "swimEndHours" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "swimRampPercent" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "bikeStartHours" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "bikeEndHours" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "bikeRampPercent" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "runStartHours" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "runEndHours" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "runRampPercent" DOUBLE PRECISION;

ALTER TABLE "SeasonMesocycle"
  ADD COLUMN IF NOT EXISTS "swimSplitPercent" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "bikeSplitPercent" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "runSplitPercent" DOUBLE PRECISION;
