-- Simple season planner: per-discipline season ramp defaults and phase ramp toggles

ALTER TABLE "SeasonPlan"
  ADD COLUMN IF NOT EXISTS "swimStartHours" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "swimPeakHours" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "swimRampPercent" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "bikeStartHours" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "bikePeakHours" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "bikeRampPercent" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "runStartHours" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "runPeakHours" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "runRampPercent" DOUBLE PRECISION;

ALTER TABLE "SeasonPhase"
  ADD COLUMN IF NOT EXISTS "rampSwimEnabled" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS "rampBikeEnabled" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS "rampRunEnabled" BOOLEAN NOT NULL DEFAULT true;
